# path: seal/docker-compose.yml

version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data

  app:
    container_name: seal
    image: seal:latest
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
    command: npm run start
    depends_on:
      - postgres